[workspace]
resolver = "3"
members = ["evaluation", "machine-check", "machine-core"]

[workspace.dependencies]
machine-check.path = "machine-check"
machine-core.path = "machine-core"
serde = { version = "1.0.159", features = ["derive"] }
walkdir = "2.5.0"
serde_json = "1.0.95"